version: '3.1'

services:

  shedlock-service-1:
    image: ghcr.io/tomasz-galuszka/shedlock:${MICROSERVICE_VERSION}
    environment:
      DATABASE_HOST: mongo-service
      DATABASE_PORT: 27017
      DATABASE_NAME: admin
      DATABASE_USER: local_user
      DATABASE_PASSWORD: local_pass
      DATABASE_PROTOCOL: mongodb

  shedlock-service-2:
    image: ghcr.io/tomasz-galuszka/shedlock:${MICROSERVICE_VERSION}
    environment:
      DATABASE_HOST: mongo-service
      DATABASE_PORT: 27017
      DATABASE_NAME: admin
      DATABASE_USER: local_user
      DATABASE_PASSWORD: local_pass
      DATABASE_PROTOCOL: mongodb

  shedlock-service-3:
    image: ghcr.io/tomasz-galuszka/shedlock:${MICROSERVICE_VERSION}
    environment:
      DATABASE_HOST: mongo-service
      DATABASE_PORT: 27017
      DATABASE_NAME: admin
      DATABASE_USER: local_user
      DATABASE_PASSWORD: local_pass
      DATABASE_PROTOCOL: mongodb

  mongo-service:
    image: mongo:${MONGO_DB_VERSION}
    environment:
      MONGO_INITDB_ROOT_USERNAME: local_user
      MONGO_INITDB_ROOT_PASSWORD: local_pass
      MONGO_INITDB_DATABASE: shedlock-db
    ports:
      - "27017:27017"
