version: '3.1'

services:

  shedlock-service:
    image: ghcr.io/tomasz-galuszka/shedlock:${MICROSERVICE_VERSION}
    environment:
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_NAME: shedlock-db
      DATABASE_USER: local_user
      DATABASE_PASSWORD: local_pass
      DATABASE_PROTOCOL: mongodb
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9090"
    ports:
      - "8080:8080"
      - "9090:9090"

  mongo:
    image: mongo:${MONGO_DB_VERSION}
    environment:
      MONGO_INITDB_ROOT_USERNAME: local_user
      MONGO_INITDB_ROOT_PASSWORD: local_pass
      MONGO_INITDB_DATABASE: shedlock-db
    ports:
      - "27017:27017"
#    volumes:
#      - ./init.js:/docker-entrypoint-initdb.d/init.js